### ISSUE TITLE
SEO enhance follow up

### ISSUE THREAD

**Issue by sandralut** [livingbio/www.gliacloud.com#17]
．已增加 img 的 alt 內容
．已有sitemap（已建過）
．已建 robots.txt
．已增加meta language（for Bing）
．已增加 hreflang （Google Web master 建議）
．已增加 meta description

**Comment by sandralut** [comment]
Web Master 其他建議：
．選偏好版本（選擇網站在 Google 搜尋中顯示時是否要加上「www」）------不確定是否該做

**Comment by sandralut** [comment]
官網的關鍵字調整建議：
https://www.evernote.com/shard/s246/sh/6f33fff0-d414-4a30-a9e0-6a2a551e8ab4/18e20693c9ab3b55

註：查了資料，很多人都建議關鍵字出現的頻率高並沒有用，所以原則為把希望是關鍵字的字放上去，而不追求重複率

**Comment by lucemia** [comment]
1. sitemap 重新上傳
2. 定期紀錄 SEO 效果

**Comment by sandralut** [comment]
sitemap 已更新

**Comment by lucemia** [comment]
@sandralut 

There are some free seo report tool you can check
https://www.woorank.com/en/www/gliacloud.com

Google Page speed 
https://developers.google.com/speed/pagespeed/insights/?hl=zh-CN&url=https%3A%2F%2Fwww.gliacloud.com%2Fen%2F
