### ISSUE TITLE
GliaCloud privacy policy

### ISSUE THREAD

**Issue by lucemia** [livingbio/www.gliacloud.com#23]
> Privacy Policy
> 
> At gliacloud, the privacy of our visitors is of extreme importance to us. This privacy policy governs and lists the main privacy principles we apply the data we collect through our service.
> 
> Our Service
> 
> GliaCloud provides programmatic advertising service. We work with companies that will use ad spaces to offer you discounts, announce new products, and make recommendations that we think you'll like based on totally anonymous info. All we recognize about you is your browser, and we do not collect or store any personal information about you. With our service, you will be able to receive personalized ads that are more relevant for you than the common advertising ways.
> 
> Privacy Policy
> 
> If you require any more information or have any questions about our privacy policy, please feel free to contact us by email at info@gliacloud.com.
> GliaCloud may update its Privacy Policy from time to time. When we change the policy in a material way, a notice will be posted on our website along with the updated Privacy Policy.
> To make sure your personal information is secure, we strictly enforce privacy safeguards within the company. GliaCloud is dedicated to providing the best Quality, Value and Service to meet our customers’ needs.

please ref:
https://www.codeme.cc/privacy/

加在這頁
https://www.gliacloud.com/en/privacy/

**Comment by georgefs** [comment]
補說明, 
現在需要在www.gliacloud.com 上面新增privacy policy 
採用舊版樣板即可 https://www.gliacloud.com/zh-hant/company/

1. header tab 需要新增 Privacy Policy 欄位
2. 新增 Privacy Policy 頁面
3. 需連結 /privacy  至該頁面

i18n 翻譯先暫緩

**Comment by lucemia** [comment]
不用翻譯

**Comment by lucemia** [comment]
Privacy Policy Statement

This privacy policy statement (“Privacy Statement”) applies to the treatment of personally identifiable information submitted by, or otherwise obtained from, you in connection with the associated application (“Application”). The Application is provided by GliaCloud. By using or otherwise accessing the Application, you acknowledge that you accept the practices and policies outlined in this Privacy Statement. 

WHAT PERSONAL INFORMATION DOES GLIACLOUD COLLECT? 

We collect the following types of information from our users: 

Personal Information You Provide to Us:
We may receive and store any information you submit to the Application (or otherwise authorize us to obtain – such as, from (for example) your Facebook account). The types of personal information collected may include your full name, email address, gender, IP address, browser information, username, demographic information, and any other information necessary for us to provide the Application services. 

Personal Information Collected Automatically:
We receive and store certain types of usage related information whenever you interact with Application. For example, GliaCloud may automatically receive and record information regarding your computer’s IP address, browser information, Facebook user ID, Facebook Page fan status, and URLs accessed. 

HOW DOES GLIACLOUD USE THE INFORMATION IT COLLECTS? 

GliaCloud uses the information described in this Privacy Statement (i) internally, to analyze, develop and improve its products and services, and (ii) as set forth below in the “Will GLIACLOUD Share any of the personal information it Collects” section below. 

WILL GLIACLOUD SHARE ANY OF THE PERSONAL INFORMATION IT RECEIVES? 

Personal information about our users is an integral part of our business. We neither rent nor sell your personal information to anyone. We share your personal information only as described below. 

Agents: We may employ other companies and people to perform tasks on our behalf and need to share your information with them to provide products or services to you. Unless we tell you differently, GliaCloud’s agents do not have any right to use personal information we share with them beyond what is necessary to assist us. You hereby consent to our sharing of personal information for the above purposes. 

Business Transfers: In some cases, we may choose to buy or sell assets. In these types of transactions, customer information is typically one of the business assets that are transferred. Moreover, if GliaCloud, or substantially all of its assets were acquired, or in the unlikely event that GliaCloud goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of GliaCloud may continue to use your personal information as set forth in this policy. 

Protection of GliaCloud and Others: We may release personal information when we believe in good faith that release is necessary to comply with the law; enforce or apply our conditions of use and other agreements; or protect the rights, property, or safety of GliaCloud, our employees, our users, or others. This includes exchanging information with other companies and organizations for fraud protection and credit risk reduction. 

With Your Consent: Except as set forth above, you will be notified when your personal information may be shared with third parties, and will be able to prevent the sharing of this information. 

CONDITIONS OF USE. 

If you decide to use or otherwise access the Application, your use/access and any possible dispute over privacy is subject to this Privacy Statement and our Terms of Use, including limitations on damages, arbitration of disputes, and application of Taiwan law. 

THIRD PARTY APPLICATIONS/WEBSITES. 

The Application may permit you to link to other applications or websites. Such third party applications/websites are not under GliaCloud’s control, and such links do not constitute an endorsement by GliaCloud of those other applications/websites or the services offered through them. The privacy and security practices of such third party application/websites linked to the Application are not covered by this Privacy Statement, and GliaCloud is not responsible for the privacy or security practices or the content of such websites. 

CHANGES TO THIS PRIVACY STATEMENT. 

GliaCloud may amend this Privacy Statement from time to time. Use of information we collect now is subject to the Privacy Statement in effect at the time such information is used. If we make changes in the way we use personal information, we will notify you by posting an announcement on our Site. Users are bound by any changes to the Privacy Statement when he or she uses or otherwise accesses the Application after such changes have been first posted. 

QUESTIONS OR CONCERNS. 

If you have any questions or concerns regarding privacy on our Website, please send us a detailed message at info@gliacloud.com. We will make every effort to resolve your concerns. 

Effective Date: January 1st, 2016

**Comment by hsu022210** [comment]
最上面的Privacy Policy Statement三個字是否也打算要和其他標題一樣全大寫呢?
還是照目前comment上這樣就好?

**Comment by lucemia** [comment]
全大寫吧

**Comment by hsu022210** [comment]
fixed https://github.com/livingbio/www.gliacloud.com/issues/23

**Comment by lucemia** [comment]
@hsu022210  不好意思 請改成只有第一個字的首字母大寫
`Privacy Policy Statement` -> `Privacy policy statement`

**Comment by hsu022210** [comment]
沒關係, 那其他標題也要照這規則嗎? 還是只要Privacy policy statement這樣就好?

**Comment by lucemia** [comment]
全部的標題都按照這個規則
